# Generated by Django 2.1.2 on 2018-10-26 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateTimeField(help_text='Date format yyyy-mm-dd')),
                ('notify_me_before', models.DateTimeField(default=1, help_text='Mention number of hours before you want to get notified. Default is 1 hour')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', help_text='Choose either Pending or Completed for status', max_length=20)),
                ('soft_del', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
