# Generated by Django 2.1.2 on 2018-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='soft_del',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
