# Generated by Django 2.1.2 on 2018-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_soft_del'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pending',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
