# Generated by Django 2.1.2 on 2018-10-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181024_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 15, 11, 16, 314060)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', help_text='Choose either Pending or Completed for status', max_length=20),
        ),
    ]
