# Generated by Django 2.1.2 on 2018-10-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181026_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='notify_me_before',
            new_name='notify_before',
        ),
    ]
