# Generated by Django 2.1.2 on 2018-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181026_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='soft_del_timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
