# Generated by Django 2.1.2 on 2018-10-25 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181025_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 14, 51, 22, 417770)),
        ),
    ]
