# Generated by Django 2.1.2 on 2018-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_soft_del_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='soft_del_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
