# Generated by Django 2.1.2 on 2018-11-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181029_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_title', models.CharField(blank=True, help_text='If you want to add optional sub-tasks you can do it here.', max_length=100, null=True)),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Task')),
            ],
        ),
    ]
