# Generated by Django 2.1.2 on 2018-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notify_before',
            field=models.IntegerField(default=1, help_text="Mention number of hours before 'Due-Date' you want to get notified. Default is 1 hour", null=True),
        ),
    ]
