# Generated by Django 2.1.2 on 2018-11-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181105_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task')),
            ],
        ),
    ]
