# Generated by Django 2.1.2 on 2018-10-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181025_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 15, 16, 2, 564153)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 15, 16, 2, 564179)),
        ),
    ]
