# Generated by Django 2.1.2 on 2018-11-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alerttasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertTasks',
            new_name='AlertTask',
        ),
    ]
