# Generated by Django 2.1.2 on 2018-10-25 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181025_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 15, 37, 17, 988656), help_text='Date format yyyy-mm-dd'),
        ),
    ]
