# Generated by Django 2.1.2 on 2018-10-25 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20181025_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 10, 14, 56, 893725, tzinfo=utc)),
        ),
    ]
