# Generated by Django 2.1.2 on 2018-10-25 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181025_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 15, 49, 42, 801575)),
        ),
    ]
