# Generated by Django 2.1.2 on 2018-10-25 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20181025_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 17, 7, 46, 564481)),
        ),
    ]
