# Generated by Django 2.1.2 on 2018-10-25 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20181025_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='Date format yyyy-mm-dd'),
        ),
    ]
